apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: vault-shim-location
  description: Links to additional entities in the vault-shim repository.
  annotations:
    github.com/project-slug: Bandwidth/vault-shim
spec:
  targets:
    - ./component.yaml
    # - add more components using relative filepaths here
    # - you may also rename/move the original component.yaml file
