name: Draft Release

on:
  push:
    branches:
      - main

jobs:
  draft-release:
    environment: staging
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # Drafts your next Release notes as Pull Requests are merged
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: draft_release.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
